#!/bin/bash

set -e

SECURITY_CHECKER='./security-checker.bin'

pushd $(dirname $0)

if [ ! -e $SECURITY_CHECKER ] && [ $(uname) = "Darwin" ]
then
    curl -L https://github.com/fabpot/local-php-security-checker/releases/download/v1.2.0/local-php-security-checker_1.2.0_darwin_amd64 -o $SECURITY_CHECKER && chmod +x $SECURITY_CHECKER
fi

if [ ! -e $SECURITY_CHECKER ] && [ $(uname) = "Linux" ]
then
    curl -L https://github.com/fabpot/local-php-security-checker/releases/download/v1.2.0/local-php-security-checker_1.2.0_linux_amd64 -o $SECURITY_CHECKER && chmod +x $SECURITY_CHECKER
fi

if [ ! -e $SECURITY_CHECKER ] && [ $(uname) = "Windows" ]
then
    curl -L https://github.com/fabpot/local-php-security-checker/releases/download/v1.2.0/local-php-security-checker_1.2.0_windows_amd64 -o $SECURITY_CHECKER && chmod +x $SECURITY_CHECKER
fi

$SECURITY_CHECKER $@

